SELECT * FROM DEPT_MANAGER;
USE EMPLOYEES;
SELECT *
FROM DEPT_MANAGER 
WHERE EMP_NO IN (SELECT EMP_NO FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN'1990-01-01' AND '1995-01-01');

SELECT E.* FROM EMPLOYEES E 
WHERE E.EMP_NO IN (SELECT DM.EMP_NO FROM DEPT_MANAGER DM);

SELECT E.FIRST_NAME, E.LAST_NAME
FROM EMPLOYEES E
WHERE EXISTS(SELECT * FROM DEPT_MANAGER DM
WHERE E.EMP_NO = DM.EMP_NO)
ORDER BY EMP_NO;

SELECT * FROM EMPLOYEES E 
WHERE EXISTS( SELECT * FROM TITLES T
WHERE T.EMP_NO = E.EMP_NO AND T.TITLE ='Assistant Engineer');

SELECT F.* FROM (SELECT E.EMP_NO AS EMPLOYEE_ID,
MIN(DE.DEPT_NO) AS DEPARTMENT_CODE,
(SELECT EMP_NO FROM EMPLOYEES 
WHERE EMP_NO = 110022) AS MANAGER_ID
FROM EMPLOYEES E JOIN DEPT_EMP DE ON E.EMP_NO = DE.EMP_NO
WHERE E.EMP_NO <= 10020
GROUP BY E.EMP_NO
ORDER BY E.EMP_NO) AS F;

INSERT INTO EMP_MANAGER 
SELECT U.* FROM (

    SELECT A.* FROM (
            SELECT E.EMP_NO AS EMPLOYEE_ID,
            MIN(DE.DEPT_NO) AS DEPARTMENT_CODE,
            (SELECT 
                    EMP_NO
                FROM
                    EMPLOYEES
                WHERE
                    EMP_NO = 110022) AS MANAGER_ID
    FROM
        EMPLOYEES E
    JOIN DEPT_EMP DE ON E.EMP_NO = DE.EMP_NO
    WHERE
        E.EMP_NO <= 10020
    GROUP BY E.EMP_NO
    ORDER BY E.EMP_NO ) AS A
    
UNION 

SELECT B.*
FROM
    (SELECT 
        E.EMP_NO AS EMPLOYEE_ID,
            MIN(DE.DEPT_NO) AS DEPARTMENT_CODE,
            (SELECT 
                    EMP_NO
                FROM
                    EMPLOYEES
                WHERE
                    EMP_NO = 110039) AS MANAGER_ID
    FROM
        EMPLOYEES E
    JOIN DEPT_EMP DE ON E.EMP_NO = DE.EMP_NO
    WHERE
        E.EMP_NO BETWEEN 10021 AND 10040
    GROUP BY E.EMP_NO
    ORDER BY E.EMP_NO) AS B
    
    
    UNION 
    SELECT C.*
FROM
    (SELECT 
        E.EMP_NO AS EMPLOYEE_ID,
            MIN(DE.DEPT_NO) AS DEPARTMENT_CODE,
            (SELECT 
                    EMP_NO
                FROM
                    EMPLOYEES
                WHERE
                    EMP_NO = 110039) AS MANAGER_ID
    FROM
        EMPLOYEES E
    JOIN DEPT_EMP DE ON E.EMP_NO = DE.EMP_NO
    WHERE
        E.EMP_NO = 110022
    GROUP BY E.EMP_NO
    ORDER BY E.EMP_NO) AS C
    
    UNION 
    
    SELECT D.*
FROM
    (       SELECT E.EMP_NO AS EMPLOYEE_ID,
            MIN(DE.DEPT_NO) AS DEPARTMENT_CODE,
            (SELECT 
                    EMP_NO
                FROM
                    EMPLOYEES
                WHERE
                    EMP_NO = 110022) AS MANAGER_ID
    FROM
        EMPLOYEES E
    JOIN DEPT_EMP DE ON E.EMP_NO = DE.EMP_NO
    WHERE
        E.EMP_NO = 110039
    GROUP BY E.EMP_NO
    ORDER BY E.EMP_NO) AS D) AS U;
    
    SELECT * FROM EMP_MANAGER;
    
    DROP TABLE IF EXISTS EMP_MANAGER;
    CREATE TABLE IF NOT EXISTS EMP_MANAGER
    (
     EMP_NO INT(11)  NOT NULL,
     DEPT_NO CHAR(4) NULL,
     MANAGER_NO INT(11)  NOT NULL
            );
            
            USE EMPLOYEES;
            
    SELECT E1.* 
    FROM EMP_MANAGER E1
    JOIN EMP_MANAGER E2 ON E1.EMP_NO = E2.MANAGER_NO;
    
    
    SELECT * FROM EMP_MANAGER
    ORDER BY EMP_MANAGER.EMP_NO;
    
    
    SELECT * FROM EMP_MANAGER;
    
    CREATE OR REPLACE VIEW V_DEPT_EMP_LATEST_DATE AS
    SELECT EMP_NO, MAX(FROM_DATE) AS FROM_DATE, MAX(TO_DATE) AS TO_DATE FROM DEPT_EMP
    GROUP BY EMP_NO;
    
    CREATE OR REPLACE VIEW V_AVERAGE_SALARY AS 
    SELECT DM.EMP_NO, FROM DEPT_MANAGER DM
    JOIN SALARIES S ON S.EMP_NO = DM.EMP_NO
    ORDER BY EMP_NO;
    
    CREATE OR REPLACE VIEW V_AVERAGE_SALARY1 AS 
    SELECT DM.EMP_NO, ROUND(AVG(S.SALARY),2) AS SALARY
    FROM SALARIES S JOIN DEPT_MANAGER DM ON DM.EMP_NO = S.EMP_NO
    ORDER BY EMP_NO;
    
